about/urls.py
from django.urls import path
from . import views

app_name = 'about'

from property.views import property_detail
urlpatterns = [
    path('',views.aboutus, name='aboutus'),
]

agents/urls.py
from django.urls import path
from . import views

app_name = 'agents'

from property.views import property_detail
urlpatterns = [
    path('',views.agents_list, name='agents_list'),
]

contact/urls.py
from django.urls import path
from . import views


app_name = 'contact'


urlpatterns = [
    path('', views.send_mail, name='send_mail'),
    path('succes/', views.succes, name='succes'),

]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'


urlpatterns = [
    path('', views.home, name='home'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('property', include('property.urls', namespace='property')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('about/', include('about.urls', namespace='about')),
    path('contact/', include('contact.urls', namespace='contact')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'HOTEL RESERVATION ADMIN'
admin.site.site_title = 'HOTEL RESERVATION ADMIN'
admin.site.site_index_title = 'Welcome to hotel reservation administration'

property/urls.py
from django.urls import path
from . import views

app_name = 'property'

from property.views import property_detail
urlpatterns = [
    path('',views.property_list, name='property_list'),
    path('<int:id>',views.property_detail, name='property_detail'),
]

about/models.py
from django.db import models

# Create your models here.
class About(models.Model):
    vision = models.TextField()
    mission = models.TextField()
    image = models.ImageField(upload_to='about/')

    def __str__(self):
        return str(self.id)

agents/models.py
from django.db import models

# Create your models here.
class Agent(models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='agents/')


    def __str__(self):
        return self.name

contact/models.py
from django.db import models

# Create your models here.
class ContactDetails(models.Model):
    # location =
    email = models.EmailField()
    phone_number = models.CharField(max_length=15)

    def __str__(self):
        return str(self.id)

home/models.py
from django.db import models

# Create your models here.

property/models.py
from django.db import models

# Create your models here.
property_type = [
    ('sale', "sale"),
    ('rent', "rent")
]
                  

class Property(models.Model):
    name = models.CharField(max_length=50)
    property_type = models.CharField(choices=property_type, max_length=10)
    price = models.PositiveBigIntegerField()  
    category = models.ForeignKey('Category', null=True, on_delete=models.SET_NULL)
    area = models.DecimalField(decimal_places=2, max_digits=10)
    beds_number = models.PositiveIntegerField()
    baths_number = models.PositiveIntegerField()
    garages_number = models.PositiveIntegerField()
    image = models.ImageField(upload_to='property/', null=True)
    location = models.CharField(max_length=50, null=True)
    
    
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Property'
        verbose_name_plural = 'Properties'

   
  
class Category(models.Model):
    category_name = models.CharField(max_length=30)
    image = models.ImageField(upload_to='category/', null=True)

    
    def __str__(self):
        return self.category_name


    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Reserve(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    notes = models.TextField()

    def __str__(self):
        return self.name

contact/forms.py
from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField()
    from_email = forms.EmailField(required=True)
    message = forms.CharField(widget=forms.Textarea , required=True)

property/forms.py
from django import  forms
from .models import Reserve, Property

class ReserveForm(forms.ModelForm):
    class Meta :
        model = Reserve
        fields = '__all__'

"""class PropertySearch(forms.ModelForm):
    class Meta :
        model = Property
        # fields = ['address', 'property_type']"""

about/views.py
from django.shortcuts import render

# Create your views here.
from .models import About


def aboutus(request):
    about = About.objects.last()
    template = 'about/about.html'
    context = {
        'about' : about

    }
    return render(request , template , context)

agents/views.py
from django.shortcuts import render
from .models import Agent
# Create your views here.
def agents_list(request):
    agent_list = Agent.objects.all()
    template = 'agents/agents.html'
    context = {
        'agent_list' : agent_list
    }

    return render(request, template, context)

contact/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm
# Create your views here.
from .models import ContactDetails
from django.core.mail import BadHeaderError
from django.core.mail import send_mail as sm
from django.http import HttpResponse , HttpResponseRedirect



def send_mail(request):
    contactdetails = ContactDetails.objects.last()
    template = 'contact/contact.html'

    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            subject = contact_form.cleaned_data['subject']
            from_email = contact_form.cleaned_data['from_email']
            message = contact_form.cleaned_data['message']

            try:
                sm(subject, message, from_email, ['test@gmail.com'] )
            except BadHeaderError :
                return HttpResponse('invalid header')
            return  redirect('contact:succes')
    else:
        contact_form = ContactForm()
    context = {
        'contactdetails' : contactdetails,
        'contact_form' : contact_form
    }

    return render(request, template, context)


def succes(request):
    return HttpResponse('Message sent succesfully.')

home/views.py
from django.shortcuts import render
from property.models import Property, Category
from agents.models import Agent
from django.http import HttpResponse
from django.db.models import Count
# Create your views here.


def home(request):
    category_list = Category.objects.annotate(property_count=Count('property')).values('category_name', 'property_count', 'image')

    property_list = Property.objects.all()
    agents_list = Agent.objects.all()
    template = 'home/home.html'
    context = {
        'category_list_home' : category_list,
        'property_list_home' : property_list,
        'agents_list_home' : agents_list,
    }

    return render(request, template, context)

property/views.py
from django.shortcuts import render
from .models import Property, Category
from .forms import ReserveForm, Property
from django.db.models import Q
def property_list(request):
    property_list = Property.objects.all()
    template = 'property/list.html'

    address_query = request.GET.get('q')
    property_type = request.GET.get('property_type', None)
    if address_query and property_type:
        property_list = property_list.filter(
        Q(name__icontains=address_query) &
        Q(property_type__icontains=property_type[0])
        ).distinct()
    print(property_list)
    context = {
        'property_list': property_list,
    }

    return render(request, template, context)
    context = {
        'property_list': property_list    
    }
    
    return render(request, template, context)



def property_detail(request, id):
    property_detail = Property.objects.get(id=id)
    template = 'property/detail.html'

    if request.method == 'POST':
        reserve_form = ReserveForm(request.POST)
        if reserve_form.is_valid():
            reserve_form.save()

    else:
        reserve_form = ReserveForm()

    context = {
        'property_detail': property_detail,
        'reserve_form' : reserve_form
    }
    
    return render(request, template, context)

about/templates/about/about.html
{% extends 'base.html' %}

{% block body %}
  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span>About</span>
              </div>
              <h1>About Us</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(img/slider_1.jpg);"></li>
      <li style="background-image: url(img/slider_4.jpg);"></li>
      <li style="background-image: url(img/slider_2.jpg);"></li>
    </ul>
  </section>
  <!-- END: slider  -->

  <section class="probootstrap-section">
    <div class="container">
      <div class="row heading">
        <div class="col-md-12"><h2 class="mt0 mb50 text-center">Our Company</h2></div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p><img src="{{about.image.url}}" class="img-responsive" alt="Free Bootstrap Template by uicookies.com"></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <h2>Our Mission</h2>
          <p>{{about.mission}}</p>
        </div>
        <div class="col-md-6">
          <h2>Our Vision</h2>
          <p>{{about.vision}}</p>
        </div>
      </div>
    </div>
  </section>

 {% endblock body %}

agents/templates/agents/agents.html
{% extends 'base.html' %}
{% block body %}



  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span>Agents</span>
              </div>
              <h1>Agents</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(img/slider_1.jpg);"></li>
      <li style="background-image: url(img/slider_4.jpg);"></li>
      <li style="background-image: url(img/slider_2.jpg);"></li>
    </ul>
  </section>
  <!-- END: slider  -->
  
  <section class="probootstrap-section probootstrap-section-lighter">
    <div class="container">
      <div class="row heading">
        <h2 class="mt0 mb50 text-center">Our Agents</h2>
      </div>
      <div class="row">
        {% for agent in agent_list %}
          <div class="col-md-3 col-sm-6">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{{agent.image.url}}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">{{agent.name}}</h2>
              <p><small>{{agent.title}}</small></p>
            </div>
          </div>
        </div>
        {% endfor %}




      </div>
    </div>
  </section>



 {% endblock body %}

contact/templates/contact/contact.html
{% extends 'base.html' %}
{% block body %}




  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span>About</span>
              </div>
              <h1>Contact</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(img/slider_1.jpg);"></li>
      <li style="background-image: url(img/slider_4.jpg);"></li>
      <li style="background-image: url(img/slider_2.jpg);"></li>
    </ul>
  </section>
  <!-- END: slider  -->


  <section class="probootstrap-section">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <form method="post" class="probootstrap-form mb60">
            {% csrf_token %}
            {{contact_form}}

            <div class="form-group">
              <input type="submit" class="btn btn-primary" id="submit" name="submit" value="Send Message">
            </div>
          </form>
        </div>
        <div class="col-md-3 col-md-push-1">
          <h4>Contact Details</h4>
          <ul class="with-icon colored">
            <li><i class="icon-location2"></i> <span>Hotel Papaláš, Podnikatelova 1, Harrachov, Česká republika</span></li>
            <li><i class="icon-mail"></i><span>{{contactdetails.email}}</span></li>
            <li><i class="icon-phone2"></i><span>{{contactdetails.phone_number}}</span></li>
          </ul>

          <h4>Feedback</h4>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          <p><a href="#">Learn More</a></p>
        </div>
      </div>
    </div>
  </section>  
  <div id="map"></div>
  

 {% endblock body %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

  <section class="probootstrap-section">
    <div class="container">
      <div class="row heading">
        <h2 class="mt100 mb50 text-center">Naše hotely</h2>
      </div>

      <div class="row probootstrap-gutter10">
        {% for category_list in category_list_home %}
           <div class="col-md-6 col-sm-6">
            <a href="#" class="probootstrap-hover-overlay">
            <img src="media/{{category_list.image}}" class="img-responsive">
            <div class="probootstrap-text-overlay">
              <h3>{{category_list.category_name}}</h3>
              <p>{{category_list.property_count}} Properties</p>
            </div>
          </a>
        </div>
        {% endfor %}

      </div>
    </div>
  </section>
  <!-- END: section -->


  <section class="probootstrap-section probootstrap-section-lighter">
    <div class="container">
      <div class="row heading">
        <h2 class="mt0 mb50 text-center">Akční nabídka</h2>
      </div>
      <div class="row">
        {% for property in property_list_home %}
            <div class="col-md-4 col-sm-6">
          <div class="probootstrap-card probootstrap-listing">
            <div class="probootstrap-card-media">
              <img src="{{property.image.url}}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading"><a href="#">{{property}}</a></h2>
              <div class="probootstrap-listing-location">
                <i class="icon-location2"></i> <span>{{property.location}}</span>
              </div>
              <!--<div class="probootstrap-listing-category for-sale"><span>for {{property.property_type}}</span></div>-->
              <div class="probootstrap-listing-price"><strong>{{property.price}}</strong> / za osobu a noc</div>
            </div>
            <div class="probootstrap-card-extra">
              <ul>
                <li>
                  Plocha
                  <span>{{property.area}}</span>
                </li>
                <li>
                  Lůžka
                  <span>{{property.beds_number}}</span>
                </li>
                <li>
                  Koupelny
                  <span>{{property.baths_number}}</span>
                </li>
                <li>
                  Parkování
                  <span>{{property.garages_number}}</span>
                </li>
              </ul>
            </div>
          </div>
          <!-- END listing -->
        </div>
        {% endfor %}
      </div>
    </div>
  </section>

  <section class="probootstrap-section probootstrap-section-lighter">
    <div class="container">
      <div class="row heading">
        <h2 class="mt0 mb50 text-center">Naši manažeři</h2>
      </div>
      <div class="row">
        {% for agent in agents_list_home %}
           <div class="col-md-3">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{{agent.image.url}}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">{{agent.name}}</h2>
              <p><small>{{agent.title}}</small></p>
            </div>
          </div>
        </div>
        {% endfor %}

      </div>
    </div>
  </section>


{% endblock body %}

property/templates/property/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span><a href="{% url 'property:property_list' %}"> Properties </a></span>{{property_detail}}
              </div>
              <h1>{{property_detail}}</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(img/slider_1.jpg);"></li>
      <li style="background-image: url(img/slider_4.jpg);"></li>
      <li style="background-image: url(img/slider_2.jpg);"></li>
    </ul>
  </section>
  <!-- END: slider  -->

  <section class="probootstrap-section">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p><img src="{{property_detail.image.url}}" class="img-responsive" alt="Free Bootstrap Template by uicookies.com"></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h2>Details</h2>

          <p>Type : {{property_detail.property_type}}</p>
          <p>Area : {{property_detail.area}} m2</p>
          <p>Beds : {{property_detail.beds_number}}</p>
          <p>Baths : {{property_detail.baths_number}}</p>
          <p>Garages : {{property_detail.garages_number}}</p>
        </div>

      </div>
    </div>
  </section>

<section class="probootstrap-section">
    <div class="container">

      <div class="row">
        <div class="col-md-12">
          <h2>Reserve This Property</h2>
            <form action="" method="POST">
              {% csrf_token %}
              {% bootstrap_form reserve_form %}
              {% buttons %}
              <button type="submit" class="btn btn-primary">Reserve</button>
              {% endbuttons %}

            </form>
        </div>

      </div>
    </div>
  </section>

{% endblock body %}

property/templates/property/list.html
{% extends "base.html" %}



{% block body %}


  <!-- END: header -->
  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span>Properties</span>
              </div>
              <h1>Properties</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(img/slider_1.jpg);"></li>
      <li style="background-image: url(img/slider_4.jpg);"></li>
      <li style="background-image: url(img/slider_2.jpg);"></li>
    </ul>
  </section>
  
  <section class="probootstrap-section probootstrap-section-lighter">
    <div class="container">
      <div class="row">
        {% if property_list %}
          {% for property in property_list %}
            <div class="col-md-4 col-sm-6">
              <div class="probootstrap-card probootstrap-listing">
                <div class="probootstrap-card-media">
                  <img src="{{property.image.url}}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
                </div>
                <div class="probootstrap-card-text">
                  <h2 class="probootstrap-card-heading"><a href="{% url 'property:property_detail' property.id %}">{{property}}</a></h2>
                  <div class="probootstrap-listing-location">
                    <i class="icon-location2"></i> <span>360 W Wellington Chicago, IL 60657</span>
                  </div>
                  <div class="probootstrap-listing-category for-sale"><span>for {{property.property_type}}</span></div>
                  <div class="probootstrap-listing-price"><strong>{{property.price}}</strong> / month</div>
                </div>
                <div class="probootstrap-card-extra">
                  <ul>
                    <li>
                      Area
                      <span>{{property.area}} m2</span>
                    </li>
                    <li>
                      Beds
                      <span>{{property.beds_number}}</span>
                    </li>
                    <li>
                      Baths
                      <span>{{property.baths_number}}</span>
                    </li>
                    <li>
                      Garages
                      <span>{{property.garages_number}}</span>
                    </li>
                  </ul>
                </div>
              </div>
              <!-- END listing -->
            </div>
          {% endfor %}
        {% else %}
          <div class="col-md-10 col-sm-10">
            <h2>No property with this name or type.</h2>
          </div>
        {% endif %}
      </div>
    </div>
  </section>

  {% endblock body %}

templates/base.html
{% load static %}


<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hotely Papaláš</title>
    <meta name="description" content="Free Bootstrap Theme">
    <meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">
    
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles-merged.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!--[if lt IE 9]>
      <script src="js/vendor/html5shiv.min.js"></script>
      <script src="js/vendor/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

  <!-- START: header -->
  
  <div class="probootstrap-loader"></div>

  <header role="banner" class="probootstrap-header">
    <div class="container">
        <a href="index.html" class="probootstrap-logo">Hotely Papaláš</span></a>
        
        <a href="#" class="probootstrap-burger-menu visible-xs" ><i>Menu</i></a>
        <div class="mobile-menu-overlay"></div>

        <nav role="navigation" class="probootstrap-nav hidden-xs">
          <ul class="probootstrap-main-nav">
            <li {% if category_list_home %} class="active"{% endif %}><a href="/">Domů</a></li>
            <li {% if property_list %} class="active"{% endif %}><a href="{% url 'property:property_list' %}">Nabídka</a></li>
            <li {% if agent_list %} class="active"{% endif %}><a href="{% url 'agents:agents_list' %}">Management</a></li>
            <li {% if about %} class="active"{% endif %}><a href="{% url 'about:aboutus' %}">O nás</a></li>
            <li {% if contactdetails %} class="active"{% endif %}><a href="{% url 'contact:send_mail' %}">Kontakt</a></li>
          </ul>
        </nav>
    </div>
  </header>

 {% block body %} 
 
 {% endblock body %}

  <div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-chevron-thin-up"></i></a>
  </div>
  

  <script src="{% static 'js/scripts.min.js' %}"></script>
  <script src="{% static 'js/main.min.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>

  </body>
</html>